- import_playbook: ./kubespray/cluster.yml

- hosts: kube1
  become: yes
  roles:
  - role: helm
  - role: k8s-rancher-local-path-provisioner
  - { role: k8s-namespace, k8s_namespace: "prometheus" }
  - { role: k8s-prometheus-operator, k8s_namespace: "prometheus" }
  - { role: k8s-stolon-cluster, stolon_helm_release: "stolon", k8s_namespace: "prometheus" }
